### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by xiaoxianBoy**
fix typos  
1. Fix `bin/vault-unseal/src/main.rs` typo 
2. Fix  `examples/README.md ` typo

### CODE REVIEW

**Comment by haraldh** [comment]
plz also correct the source:
```
bin/vault-unseal/src/main.rs:    info!("Inititalizing vault");
```

**Review by haraldh — APPROVED** [review]

**Comment by haraldh** [comment]
Ah, please gpg sign your commits

**Review by haraldh — APPROVED** [review]

**Review by haraldh — CHANGES_REQUESTED** [review]
why 4 commits?

**Comment by xiaoxianBoy** [comment]
> why 4 commits?

add gpg😹

**Comment by xiaoxianBoy** [comment]
> Please do the following to resign your original 2 commits:
> 
> 请执行以下操作以辞去您原来的2次提交：
> 
> ```
> $ git reset --hard HEAD~2
> $ git rebase --gpg-sign HEAD~2
> ```

ths

**Pull request closed without merging**
